### ISSUE TITLE
信点兵问题汇总

### ISSUE THREAD

**Issue by CornerOvertaking** [nico1988/plan#9]
# 信点兵问题汇总

---

1. 新增项目
    1. 去掉节点责任人，将责任人变更为项目责任人。其中项目责任人列表的数据源来自组织架构。
    2. 督办人不能选择，默认为空。当选择责任人时，自动将TA的直属上级带出来。
    3. 日期控件显示不全；原因：弹出的软键盘遮住了日期控件，建议点击日期控件时不弹出软键盘
2. 远程交互管理改成信.点兵
3. 项目详情
    1. 与【我的项目】里显示的人数不一致；其中项目详情里的参与人数据来源于部门视图里的操作，等部门视图完成后修改这个bug
    2. 阶段责任人的内容还有undefined内容；现已经取消节点责任人，项目详情直接显示项目责任人即可
4. 部门详情
    1. 部门详情的所有功能还待开发 
5. 首页
    1. 部门经理登陆后能看到所有所有人创建的项目，但是不包括研发和其他？
    2. 项目数据按照创建人分组，默认收缩。同时他自己所创建的项目默认排在第一？

**Comment by nico1988** [comment]
日期组件已经禁止软键盘完成

**Comment by nico1988** [comment]
2.远程交互管理改成信.点兵  --完成
